import NoteForm from "@/components/NoteForm/NoteForm";
import CreateNote from "@/components/CreateNote/CreateNote";
import type { Metadata } from "next";
import Modal from "@/components/Modal/Modal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
      openGraph: {
        title: `Note Hub`,
        description: "There are some notes for your attention",
        url: `https://notehub.com/notes`,
        siteName: 'NoteHub',
        images: [
          {
            url: 'https://ac.goit.global/fullstack/react/og-meta.jpg',
            width: 1200,
            height: 630,
            alt: "Note Hub",
          },
        ],
        type: 'article',
      },
};
export default function NotePage (){ 
  
      return (
      <>
       <CreateNote/>;
       <Modal onClick={close} onClose={close}>
         <NoteForm/>
       </Modal>
        
      </> 
      ) 
   }
