import { QueryClient, HydrationBoundary, dehydrate } from  "@tanstack/react-query";
import NotesClient from "./Notes.client";
import { Metadata } from "next";

type Props = {
  params: Promise<{ slug: string[] }>;
};

export async function generateMetadata(): Promise<Metadata> {
    return {
      title: `NoteHub `,
      description: "Generated by create next app",
      openGraph: {
        title: `NoteHub`,
        description: "Generated by create next app",
        url: `https://notehub.com/notes`,
        siteName: 'NoteHub',
        images: [
          {
            url: 'https://ac.goit.global/fullstack/react/og-meta.jpg',
            width: 1200,
            height: 630,
            alt: "NoteHub",
          },
        ],
        type: 'article',
      },
}
}

export default async function NotePage ({ params }: Props) {
   const queryClient = new QueryClient();
   const {slug} = await params;


   return <HydrationBoundary state={dehydrate(queryClient)}>
      <NotesClient tag={slug[0]}/>
   </HydrationBoundary>
}